export const LOAD_PLANETS_SUCCESS = 'LOAD_PLANETS_SUCCESS'

export const UPDATE_SORTING_RULES_SUCCESS = 'UPDATE_SORTING_RULES_SUCCESS'

export const UPDATE_FILTER_RULES_SUCCESS = 'UPDATE_FILTER_RULES_SUCCESS'

export const SHOW_PLANET_DETAILS_MODAL = 'SHOW_PLANET_DETAILS_MODAL'

export const HIDE_PLANET_DETAILS_MODAL = 'HIDE_PLANET_DETAILS_MODAL'

export const LOAD_RESIDENTS_SUCCESS = 'LOAD_RESIDENTS_SUCCESS'